//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aktiv.RtAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aktiv.RtAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid character set for generation activation passwords. It must be &quot;caps&quot; or &quot;digits&quot;.
        /// </summary>
        public static string ActivationPasswordInvalidCharacterSet {
            get {
                return ResourceManager.GetString("ActivationPasswordInvalidCharacterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid command params for generation activation passwords. It must be 2 command line params.
        /// </summary>
        public static string ActivationPasswordInvalidCommandParamsCount {
            get {
                return ResourceManager.GetString("ActivationPasswordInvalidCommandParamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid SM mode. It must be from 1 to 3.
        /// </summary>
        public static string ActivationPasswordInvalidSmMode {
            get {
                return ResourceManager.GetString("ActivationPasswordInvalidSmMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate activation passwords failed.
        /// </summary>
        public static string ActivationPasswordsGenerationFailed {
            get {
                return ResourceManager.GetString("ActivationPasswordsGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate activation passwords passed.
        /// </summary>
        public static string ActivationPasswordsWereGenerated {
            get {
                return ResourceManager.GetString("ActivationPasswordsWereGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на admin PIN.
        /// </summary>
        public static string AdminPin {
            get {
                return ResourceManager.GetString("AdminPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter {0}.
        /// </summary>
        public static string AdminPinChangeError {
            get {
                return ResourceManager.GetString("AdminPinChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set Admin PIN code. Must be specified for Admin PIN changing. If not specified, the default value is used.
        /// </summary>
        public static string AdminPinOption {
            get {
                return ResourceManager.GetString("AdminPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на admin.
        /// </summary>
        public static string AdminPinOwner {
            get {
                return ResourceManager.GetString("AdminPinOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Admin PIN:.
        /// </summary>
        public static string AdminPinPrompt {
            get {
                return ResourceManager.GetString("AdminPinPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AllowChangePinPolicy.
        /// </summary>
        public static string AllowChangePinPolicy {
            get {
                return ResourceManager.GetString("AllowChangePinPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN policy is modifiable by Admin: {0}.
        /// </summary>
        public static string AllowChangePinPolicyDesc {
            get {
                return ResourceManager.GetString("AllowChangePinPolicyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AllowDefaultPinUsage.
        /// </summary>
        public static string AllowDefaultPinUsage {
            get {
                return ResourceManager.GetString("AllowDefaultPinUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow default PIN-code usage: {0}.
        /// </summary>
        public static string AllowDefaultPinUsageDesc {
            get {
                return ResourceManager.GetString("AllowDefaultPinUsageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Option &quot;-{0}&quot; argument should be a number.
        /// </summary>
        public static string ArgumentMustBeIntegerType {
            get {
                return ResourceManager.GetString("ArgumentMustBeIntegerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For changing admin PIN enter old admin PIN.
        /// </summary>
        public static string ChangeAdminPinOldPinError {
            get {
                return ResourceManager.GetString("ChangeAdminPinOldPinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For changing user PIN enter old user or admin PIN.
        /// </summary>
        public static string ChangeUserPinOldPinsError {
            get {
                return ResourceManager.GetString("ChangeUserPinOldPinsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid command params count for changing volume attributes. It must be 3.
        /// </summary>
        public static string ChangeVolumeAttributesInvalidCommandParamsCount {
            get {
                return ResourceManager.GetString("ChangeVolumeAttributesInvalidCommandParamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid permanent state.
        /// </summary>
        public static string ChangeVolumeAttributesInvalidPermanentState {
            get {
                return ResourceManager.GetString("ChangeVolumeAttributesInvalidPermanentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Need to set local user pin.
        /// </summary>
        public static string ChangeVolumeAttributesNeedSetLocalPin {
            get {
                return ResourceManager.GetString("ChangeVolumeAttributesNeedSetLocalPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change volume attributes. For changing volume attributes volume owner PIN is used. If owner is user or admin while PIN isn&apos;t set, default PIN will be used. If owner is local user while local user PIN isn&apos;t set with -O option, error will be occured.
        ///[Volume id: (1 - 9)]
        ///[Access rights: (ro, rw, hi, cd)]
        ///[Change type: (p - permanent, t - temporary)].
        /// </summary>
        public static string ChangeVolumeAttributesOption {
            get {
                return ResourceManager.GetString("ChangeVolumeAttributesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing PIN error.
        /// </summary>
        public static string ChangingPinError {
            get {
                return ResourceManager.GetString("ChangingPinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Config file is empty.
        /// </summary>
        public static string ConfigFileIsEmpty {
            get {
                return ResourceManager.GetString("ConfigFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Config lines have ended.
        /// </summary>
        public static string ConfigFileLinesHaveEnded {
            get {
                return ResourceManager.GetString("ConfigFileLinesHaveEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Config file not found.
        /// </summary>
        public static string ConfigFileNotFound {
            get {
                return ResourceManager.GetString("ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration file should be set.
        /// </summary>
        public static string ConfigurationFileEmpty {
            get {
                return ResourceManager.GetString("ConfigurationFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration file path.
        /// </summary>
        public static string ConfigurationFilePathOption {
            get {
                return ResourceManager.GetString("ConfigurationFilePathOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default admin PIN will be used.
        /// </summary>
        public static string DefaultAdminPinWillBeUsed {
            get {
                return ResourceManager.GetString("DefaultAdminPinWillBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default user PIN will be used.
        /// </summary>
        public static string DefaultUserPinWillBeUsed {
            get {
                return ResourceManager.GetString("DefaultUserPinWillBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume create failed.
        /// </summary>
        public static string DriveFormatVolumeCreateFailed {
            get {
                return ResourceManager.GetString("DriveFormatVolumeCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume create passed.
        /// </summary>
        public static string DriveFormatVolumeCreateSuccess {
            get {
                return ResourceManager.GetString("DriveFormatVolumeCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на change Admin PIN.
        /// </summary>
        public static string ExampleChangeAdminPin {
            get {
                return ResourceManager.GetString("ExampleChangeAdminPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на change Admin PIN, use default new Admin PIN.
        /// </summary>
        public static string ExampleChangeAdminPinWithDefault {
            get {
                return ResourceManager.GetString("ExampleChangeAdminPinWithDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на change User PIN.
        /// </summary>
        public static string ExampleChangeUserPin {
            get {
                return ResourceManager.GetString("ExampleChangeUserPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на formatting token with generation Admin PIN with length 10 and default User PIN.
        /// </summary>
        public static string ExampleFormatWithAdminPinGeneration {
            get {
                return ResourceManager.GetString("ExampleFormatWithAdminPinGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на formatting token with default PIN codes (Admin 87654321, User 12345678).
        /// </summary>
        public static string ExampleFormatWithDefaultPins {
            get {
                return ResourceManager.GetString("ExampleFormatWithDefaultPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Examples:.
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excluded token serial number should be set in specified format (ex.: 0x46bc3390 or 932436970).
        /// </summary>
        public static string ExcludedTokenSerialEmpty {
            get {
                return ResourceManager.GetString("ExcludedTokenSerialEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excluded tokens while stream formatting [token ids in specified format: 0x46bc3390 or 932436970]. Use space as serial numbers separator or use option -E for each serial number.
        /// </summary>
        public static string ExcludedTokensOption {
            get {
                return ResourceManager.GetString("ExcludedTokensOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extended PIN policies not avaliable.
        /// </summary>
        public static string ExtendedPinPoliciesNotAvailable {
            get {
                return ResourceManager.GetString("ExtendedPinPoliciesNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Token has no flash memory.
        /// </summary>
        public static string FlashMemoryNotAvailable {
            get {
                return ResourceManager.GetString("FlashMemoryNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid access mode.
        /// </summary>
        public static string FormatDriveInvalidAccessMode {
            get {
                return ResourceManager.GetString("FormatDriveInvalidAccessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid command params count for drive formatting. It must be 4.
        /// </summary>
        public static string FormatDriveInvalidCommandParamsCount {
            get {
                return ResourceManager.GetString("FormatDriveInvalidCommandParamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid volume size.
        /// </summary>
        public static string FormatDriveInvalidVolumeSize {
            get {
                return ResourceManager.GetString("FormatDriveInvalidVolumeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formatting error.
        /// </summary>
        public static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format failed : {0} : {1} : SM mode = {2}.
        /// </summary>
        public static string FormatFailed {
            get {
                return ResourceManager.GetString("FormatFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format passed : {0} : {1} : SM mode = {2}.
        /// </summary>
        public static string FormatPassed {
            get {
                return ResourceManager.GetString("FormatPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format memory. If your device has built-in Flash memory you may specify Admin PIN, otherwise you may lose all data on it.
        /// </summary>
        public static string FormatTokenOption {
            get {
                return ResourceManager.GetString("FormatTokenOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formatting was successful.
        /// </summary>
        public static string FormatTokenSuccess {
            get {
                return ResourceManager.GetString("FormatTokenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format volume. One command for one volume. To create multiple partitions, use the appropriate number of -F commands in sequence. For partition creation admin PIN is used. If it isn&apos;t set, default admin PIN will be used.
        ///[Volume id: (1 - 9)]
        ///[Volume size: volume size in MB]
        ///[Volume owner: (a - administrator, u - user, l3-l9 - local user)]
        ///[Access rights: (ro, rw, hi, cd)].
        /// </summary>
        public static string FormatVolumeParamsOption {
            get {
                return ResourceManager.GetString("FormatVolumeParamsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate random Admin PIN code of specified length. If this command is used -a is ignored.
        /// </summary>
        public static string GenerateRandomAdminPinOption {
            get {
                return ResourceManager.GetString("GenerateRandomAdminPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate random User PIN code of specified length. If this command is used -u is ignored.
        /// </summary>
        public static string GenerateRandomUserPinOption {
            get {
                return ResourceManager.GetString("GenerateRandomUserPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generating activation password(s).
        /// </summary>
        public static string GeneratingActivationPasswords {
            get {
                return ResourceManager.GetString("GeneratingActivationPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Getting extended PIN policies.
        /// </summary>
        public static string GetExtendedPinPolicies {
            get {
                return ResourceManager.GetString("GetExtendedPinPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Getting extended PIN policies is failed.
        /// </summary>
        public static string GetExtendedPinPoliciesFailed {
            get {
                return ResourceManager.GetString("GetExtendedPinPoliciesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Illegal options.
        /// </summary>
        public static string IllegalOptions {
            get {
                return ResourceManager.GetString("IllegalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entered Admin PIN is incorrect.
        /// </summary>
        public static string IncorrectAdminPin {
            get {
                return ResourceManager.GetString("IncorrectAdminPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect OS version.
        /// </summary>
        public static string IncorrectOsVersion {
            get {
                return ResourceManager.GetString("IncorrectOsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entered PIN is incorrect.
        /// </summary>
        public static string IncorrectPin {
            get {
                return ResourceManager.GetString("IncorrectPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect volume owner PIN.
        /// </summary>
        public static string IncorrectVolumeOwnerPin {
            get {
                return ResourceManager.GetString("IncorrectVolumeOwnerPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect usage of extended PIN policy.
        /// </summary>
        public static string IncorrenctExtendedPinPolicyUsage {
            get {
                return ResourceManager.GetString("IncorrenctExtendedPinPolicyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application was initialized.
        /// </summary>
        public static string InitializedInfo {
            get {
                return ResourceManager.GetString("InitializedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid max Admin PIN retry count. It must be in the range from 3 to 10.
        /// </summary>
        public static string InvalidMaxAdminPinRetryCount {
            get {
                return ResourceManager.GetString("InvalidMaxAdminPinRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid max User PIN retry count. It must be in the range from 1 to 10.
        /// </summary>
        public static string InvalidMaxUserPinRetryCount {
            get {
                return ResourceManager.GetString("InvalidMaxUserPinRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid minimal admin PIN length. It must be from 1 to 31 symbols.
        /// </summary>
        public static string InvalidMinimalAdminPinLength {
            get {
                return ResourceManager.GetString("InvalidMinimalAdminPinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid minimal user PIN length. It must be from 1 to 31 symbols.
        /// </summary>
        public static string InvalidMinimalUserPinLength {
            get {
                return ResourceManager.GetString("InvalidMinimalUserPinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid policy value. It must be from 1 to 3.
        /// </summary>
        public static string InvalidPolicyValue {
            get {
                return ResourceManager.GetString("InvalidPolicyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid user pin change policy.
        /// </summary>
        public static string InvalidUserPinChangePolicy {
            get {
                return ResourceManager.GetString("InvalidUserPinChangePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log file path.
        /// </summary>
        public static string LogFilePathOption {
            get {
                return ResourceManager.GetString("LogFilePathOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN Login with local PIN. In order to use local user set his new PIN preliminarily.
        ///[Id: local PIN id (l3 - l9)]
        ///[PIN: local PIN].
        /// </summary>
        public static string LoginWithLocalPinOption {
            get {
                return ResourceManager.GetString("LoginWithLocalPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max PIN code attempts count for Admin PIN (count must be in the range from 3 to 10; default: 6).
        /// </summary>
        public static string MaxAdminPinAttemptsOption {
            get {
                return ResourceManager.GetString("MaxAdminPinAttemptsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max PIN code attempts count for User PIN (count must be in the range from 3 to 10; default: 6).
        /// </summary>
        public static string MaxUserPinAttemptsOption {
            get {
                return ResourceManager.GetString("MaxUserPinAttemptsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min Admin PIN code length (len must be in the range from 1 to 31; default: 6). Ignore for Rutoken S(use 1 only).
        /// </summary>
        public static string MinAdminPinLengthOption {
            get {
                return ResourceManager.GetString("MinAdminPinLengthOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MinPinLength.
        /// </summary>
        public static string MinPinLength {
            get {
                return ResourceManager.GetString("MinPinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min PIN Length: {0}.
        /// </summary>
        public static string MinPinLengthDesc {
            get {
                return ResourceManager.GetString("MinPinLengthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min User PIN code length (len must be in the range from 1 to 31; default: 6). Ignore for Rutoken S(use 1 only).
        /// </summary>
        public static string MinUserPinLengthOption {
            get {
                return ResourceManager.GetString("MinUserPinLengthOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Native library file should be set.
        /// </summary>
        public static string NativeLibraryFileEmpty {
            get {
                return ResourceManager.GetString("NativeLibraryFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to open native library at the specified path.
        /// </summary>
        public static string NativeLibraryFileInvalid {
            get {
                return ResourceManager.GetString("NativeLibraryFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Native library file doesn&apos;t exist at the specified path.
        /// </summary>
        public static string NativeLibraryFileNotExist {
            get {
                return ResourceManager.GetString("NativeLibraryFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specify a native library to use.
        /// </summary>
        public static string NativeLibraryPathOption {
            get {
                return ResourceManager.GetString("NativeLibraryPathOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid command params for using local PIN. It must be 2 command line params.
        /// </summary>
        public static string NewLocalPinInvalidCommandParamsCount {
            get {
                return ResourceManager.GetString("NewLocalPinInvalidCommandParamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid local user id.
        /// </summary>
        public static string NewLocalPinInvalidOwnerId {
            get {
                return ResourceManager.GetString("NewLocalPinInvalidOwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to set local PIN.
        /// </summary>
        public static string NewLocalPinSetFailed {
            get {
                return ResourceManager.GetString("NewLocalPinSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local PIN has been successfully set.
        /// </summary>
        public static string NewLocalPinSetSuccess {
            get {
                return ResourceManager.GetString("NewLocalPinSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old Admin PIN code. Must be specified for Admin PIN changing.
        /// </summary>
        public static string OldAdminPinOption {
            get {
                return ResourceManager.GetString("OldAdminPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Admin PIN: .
        /// </summary>
        public static string OldAdminPinPrompt {
            get {
                return ResourceManager.GetString("OldAdminPinPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old User PIN code. Must be specified for User PIN changing.
        /// </summary>
        public static string OldUserPinOption {
            get {
                return ResourceManager.GetString("OldUserPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current User PIN: .
        /// </summary>
        public static string OldUserPinPrompt {
            get {
                return ResourceManager.GetString("OldUserPinPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop after one iteration.
        /// </summary>
        public static string OneIterationOnlyOption {
            get {
                return ResourceManager.GetString("OneIterationOnlyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options:.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while sending request for setting PIN2 PINPad.
        /// </summary>
        public static string Pin2SetFailed {
            get {
                return ResourceManager.GetString("Pin2SetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN2 PINPad set request has been successfully sent.
        /// </summary>
        public static string Pin2SetSuccess {
            get {
                return ResourceManager.GetString("Pin2SetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на by admin.
        /// </summary>
        public static string PinChangeByAdmin {
            get {
                return ResourceManager.GetString("PinChangeByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN changed successfully.
        /// </summary>
        public static string PinChangedSuccess {
            get {
                return ResourceManager.GetString("PinChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} pin change failed.
        /// </summary>
        public static string PinChangeFailed {
            get {
                return ResourceManager.GetString("PinChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} pin change {1} passed : {2} : {3}.
        /// </summary>
        public static string PinChangePassed {
            get {
                return ResourceManager.GetString("PinChangePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set PIN change policy. Default value - 2.
        ///[(1 - administrator (SO) can change user PIN), (2 - user can change user PIN), (3 - both)].
        /// </summary>
        public static string PinChangePolicyOption {
            get {
                return ResourceManager.GetString("PinChangePolicyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN-codes file contains incorrect number of PINs.
        /// </summary>
        public static string PinCodesFileIncorrectLinesCount {
            get {
                return ResourceManager.GetString("PinCodesFileIncorrectLinesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN-codes file is empty.
        /// </summary>
        public static string PinCodesFileIsEmpty {
            get {
                return ResourceManager.GetString("PinCodesFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pin codes file name should be set.
        /// </summary>
        public static string PinCodesFileNameEmpty {
            get {
                return ResourceManager.GetString("PinCodesFileNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN-codes file not found.
        /// </summary>
        public static string PinCodesFileNotFound {
            get {
                return ResourceManager.GetString("PinCodesFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN-codes from file have ended.
        /// </summary>
        public static string PinCodesFilePinsHaveEnded {
            get {
                return ResourceManager.GetString("PinCodesFilePinsHaveEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PinContainsDigit.
        /// </summary>
        public static string PinContainsDigit {
            get {
                return ResourceManager.GetString("PinContainsDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN requeres digits: {0}.
        /// </summary>
        public static string PinContainsDigitDesc {
            get {
                return ResourceManager.GetString("PinContainsDigitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PinContainsLowerLetter.
        /// </summary>
        public static string PinContainsLowerLetter {
            get {
                return ResourceManager.GetString("PinContainsLowerLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN requeres lowercase chars: {0}.
        /// </summary>
        public static string PinContainsLowerLetterDesc {
            get {
                return ResourceManager.GetString("PinContainsLowerLetterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PinContainsSpecChar.
        /// </summary>
        public static string PinContainsSpecChar {
            get {
                return ResourceManager.GetString("PinContainsSpecChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN requeres spec. chars: {0}.
        /// </summary>
        public static string PinContainsSpecCharDesc {
            get {
                return ResourceManager.GetString("PinContainsSpecCharDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PinContainsUpperLetter.
        /// </summary>
        public static string PinContainsUpperLetter {
            get {
                return ResourceManager.GetString("PinContainsUpperLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN requeres uppercase chars: {0}.
        /// </summary>
        public static string PinContainsUpperLetterDesc {
            get {
                return ResourceManager.GetString("PinContainsUpperLetterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load new PIN codes from specified file. Use ont PIN per line, \n is separator. -a -u -G -g commands are ignored.
        /// </summary>
        public static string PinFilePathOption {
            get {
                return ResourceManager.GetString("PinFilePathOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t generate pin. Change Token.
        /// </summary>
        public static string PinGenerationError {
            get {
                return ResourceManager.GetString("PinGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t generate pin. This token was skipped.
        /// </summary>
        public static string PinGenerationFailed {
            get {
                return ResourceManager.GetString("PinGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PinHistoryDepth.
        /// </summary>
        public static string PinHistoryDepth {
            get {
                return ResourceManager.GetString("PinHistoryDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN history depth: {0}.
        /// </summary>
        public static string PinHistoryDepthDesc {
            get {
                return ResourceManager.GetString("PinHistoryDepthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN length and allowed PIN length mismatch. Min admin PIN length: {0}, max admin PIN length: {1}, min user PIN length: {2}, max user PIN length: {3}.
        /// </summary>
        public static string PinLengthMismatch {
            get {
                return ResourceManager.GetString("PinLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN length and allowed PIN length mismatch. Length must be in the range from 1 to 31; default: 6.
        /// </summary>
        public static string PinLengthMismatchBeforeFormat {
            get {
                return ResourceManager.GetString("PinLengthMismatchBeforeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unblock PIN failed.
        /// </summary>
        public static string PinUnlockFailed {
            get {
                return ResourceManager.GetString("PinUnlockFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unblock PIN passed.
        /// </summary>
        public static string PinUnlockSuccess {
            get {
                return ResourceManager.GetString("PinUnlockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internal error: PKCS#11 library code:.
        /// </summary>
        public static string PKCS11Error {
            get {
                return ResourceManager.GetString("PKCS11Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New random Admin PIN length and allowed PIN length mismatch, min PIN length: {0}, max PIN length: {1}.
        /// </summary>
        public static string RandomAdminPinLengthMismatch {
            get {
                return ResourceManager.GetString("RandomAdminPinLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New random User PIN length and allowed PIN length mismatch, min PIN length: {0}, max PIN length: {1}.
        /// </summary>
        public static string RandomUserPinLengthMismatch {
            get {
                return ResourceManager.GetString("RandomUserPinLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RemovePinPolicyAfterFormat.
        /// </summary>
        public static string RemovePinPolicyAfterFormat {
            get {
                return ResourceManager.GetString("RemovePinPolicyAfterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN policy will be deleted after formating: {0}.
        /// </summary>
        public static string RemovePinPolicyAfterFormatDesc {
            get {
                return ResourceManager.GetString("RemovePinPolicyAfterFormatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RestrictOneCharPin.
        /// </summary>
        public static string RestrictOneCharPin {
            get {
                return ResourceManager.GetString("RestrictOneCharPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIN requeres different char usage: {0}.
        /// </summary>
        public static string RestrictOneCharPinDesc {
            get {
                return ResourceManager.GetString("RestrictOneCharPinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Serial number should be specified.
        /// </summary>
        public static string SerialNumberEmpty {
            get {
                return ResourceManager.GetString("SerialNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specify token serial number to use.
        /// </summary>
        public static string SerialNumberOption {
            get {
                return ResourceManager.GetString("SerialNumberOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Setting extended PIN policies.
        /// </summary>
        public static string SetExtendedPinPolicies {
            get {
                return ResourceManager.GetString("SetExtendedPinPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Setting extended PIN policies is failed.
        /// </summary>
        public static string SetExtendedPinPoliciesFailed {
            get {
                return ResourceManager.GetString("SetExtendedPinPoliciesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set extended PIN policy option
        ///[Usage: --set-expp (pin_policy_opt1) (value1) (pin_policy_opt2) (value2) ... ].
        /// </summary>
        public static string SetExtendedPinPolicyOption {
            get {
                return ResourceManager.GetString("SetExtendedPinPolicyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set local PIN.
        ///[Id: local PIN id (l3 - l9)]
        ///[PIN: local PIN].
        /// </summary>
        public static string SetLocalPinOption {
            get {
                return ResourceManager.GetString("SetLocalPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activate setting PIN2-code (on the screen mode) for PINPad..
        /// </summary>
        public static string SetPin2ModeOption {
            get {
                return ResourceManager.GetString("SetPin2ModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Need to set formatting option -f.
        /// </summary>
        public static string ShouldSetFormatOption {
            get {
                return ResourceManager.GetString("ShouldSetFormatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show extended PIN policy option.
        /// </summary>
        public static string ShowExtendedPinPolicyOption {
            get {
                return ResourceManager.GetString("ShowExtendedPinPolicyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show help message.
        /// </summary>
        public static string ShowHelp {
            get {
                return ResourceManager.GetString("ShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show application version.
        /// </summary>
        public static string ShowVersion {
            get {
                return ResourceManager.GetString("ShowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set SM mode (only for Bluetooth token).
        ///[Passwords: (1 - optional password), (2 - 1 password), (3 - 6 passwords)] 
        ///[Mode: (caps - only capital letters), (digits - capital letters and digits)].
        /// </summary>
        public static string SmModeOption {
            get {
                return ResourceManager.GetString("SmModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get user and admin PINs from stdin if they value equal &quot;stdin&quot;.
        /// </summary>
        public static string StdinPinsOption {
            get {
                return ResourceManager.GetString("StdinPinsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Token Id.
        /// </summary>
        public static string TokenId {
            get {
                return ResourceManager.GetString("TokenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t change token label.
        /// </summary>
        public static string TokenLabelChangeFailed {
            get {
                return ResourceManager.GetString("TokenLabelChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Token label changed successfully.
        /// </summary>
        public static string TokenLabelChangeSuccess {
            get {
                return ResourceManager.GetString("TokenLabelChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use cp1251 for new device label.
        /// </summary>
        public static string TokenLabelCp1251Option {
            get {
                return ResourceManager.GetString("TokenLabelCp1251Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Token label should be set.
        /// </summary>
        public static string TokenLabelEmpty {
            get {
                return ResourceManager.GetString("TokenLabelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t change token label. Enter user PIN using -c.
        /// </summary>
        public static string TokenLabelPinError {
            get {
                return ResourceManager.GetString("TokenLabelPinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use UTF-8 for new device label.
        /// </summary>
        public static string TokenLabelUtf8Option {
            get {
                return ResourceManager.GetString("TokenLabelUtf8Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Token params were not set.
        /// </summary>
        public static string TokenParamsNotSet {
            get {
                return ResourceManager.GetString("TokenParamsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total disk size.
        /// </summary>
        public static string TotalDriveSize {
            get {
                return ResourceManager.GetString("TotalDriveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while getting total disk size.
        /// </summary>
        public static string TotalDriveSizeFailed {
            get {
                return ResourceManager.GetString("TotalDriveSizeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unblock user and local PINs. You should use login with Admin PIN command to unblock user and local PINs.
        /// </summary>
        public static string UnblockPinsOption {
            get {
                return ResourceManager.GetString("UnblockPinsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unhandled error:.
        /// </summary>
        public static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Usage:.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user PIN.
        /// </summary>
        public static string UserPin {
            get {
                return ResourceManager.GetString("UserPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter {0} according to user PIN change policy on token.
        /// </summary>
        public static string UserPinChangePolicyError {
            get {
                return ResourceManager.GetString("UserPinChangePolicyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set User PIN code. Must be specified for Admin PIN changing. If not specified, the default value is used.
        /// </summary>
        public static string UserPinOption {
            get {
                return ResourceManager.GetString("UserPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user.
        /// </summary>
        public static string UserPinOwner {
            get {
                return ResourceManager.GetString("UserPinOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New User PIN: .
        /// </summary>
        public static string UserPinPrompt {
            get {
                return ResourceManager.GetString("UserPinPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use UTF-8 instead of cp1251 in PIN codes.
        /// </summary>
        public static string Utf8Option {
            get {
                return ResourceManager.GetString("Utf8Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume access mode change failed.
        /// </summary>
        public static string VolumeAccessModeChangeFailed {
            get {
                return ResourceManager.GetString("VolumeAccessModeChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume access mode change passed.
        /// </summary>
        public static string VolumeAccessModeChangeSuccess {
            get {
                return ResourceManager.GetString("VolumeAccessModeChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume attributes store is not set.
        /// </summary>
        public static string VolumeAttributesStoreNotSet {
            get {
                return ResourceManager.GetString("VolumeAttributesStoreNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For -i argument should be set.
        /// </summary>
        public static string VolumeInfoEmpty {
            get {
                return ResourceManager.GetString("VolumeInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while getting volumes info.
        /// </summary>
        public static string VolumeInfoGettingFailed {
            get {
                return ResourceManager.GetString("VolumeInfoGettingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid volume id.
        /// </summary>
        public static string VolumeInfoInvalidVolumeId {
            get {
                return ResourceManager.GetString("VolumeInfoInvalidVolumeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume with specified id not found.
        /// </summary>
        public static string VolumeInfoNotFound {
            get {
                return ResourceManager.GetString("VolumeInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get volumes or drive info.
        ///[Parameter: (volume id: 1 - 9), (all volumes: a), (flash size: sz)].
        /// </summary>
        public static string VolumeInfoParamsOption {
            get {
                return ResourceManager.GetString("VolumeInfoParamsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume owners store is not set.
        /// </summary>
        public static string VolumeOwnersStoreNotSet {
            get {
                return ResourceManager.GetString("VolumeOwnersStoreNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next token... (Or press &quot;q&quot;).
        /// </summary>
        public static string WaitingNextToken {
            get {
                return ResourceManager.GetString("WaitingNextToken", resourceCulture);
            }
        }
    }
}
