//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aktiv.RtAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aktiv.RtAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character set for generation activation passwords. It must be &quot;caps&quot; or &quot;digits&quot;.
        /// </summary>
        public static string ActivationPasswordInvalidCharacterSet {
            get {
                return ResourceManager.GetString("ActivationPasswordInvalidCharacterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command params for generation activation passwords. It must be 2 command line params.
        /// </summary>
        public static string ActivationPasswordInvalidCommandParamsCount {
            get {
                return ResourceManager.GetString("ActivationPasswordInvalidCommandParamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SM mode. It must be from 1 to 3.
        /// </summary>
        public static string ActivationPasswordInvalidSmMode {
            get {
                return ResourceManager.GetString("ActivationPasswordInvalidSmMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate activation passwords failed.
        /// </summary>
        public static string ActivationPasswordsGenerationFailed {
            get {
                return ResourceManager.GetString("ActivationPasswordsGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate activation passwords passed.
        /// </summary>
        public static string ActivationPasswordsWereGenerated {
            get {
                return ResourceManager.GetString("ActivationPasswordsWereGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin PIN.
        /// </summary>
        public static string AdminPin {
            get {
                return ResourceManager.GetString("AdminPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter {0}.
        /// </summary>
        public static string AdminPinChangeError {
            get {
                return ResourceManager.GetString("AdminPinChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Admin PIN code. Must be specified for Admin PIN changing. If not specified, the default value is used.
        /// </summary>
        public static string AdminPinOption {
            get {
                return ResourceManager.GetString("AdminPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string AdminPinOwner {
            get {
                return ResourceManager.GetString("AdminPinOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Admin PIN:.
        /// </summary>
        public static string AdminPinPrompt {
            get {
                return ResourceManager.GetString("AdminPinPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended PIN policies is modifiable by Admin: {0}.
        /// </summary>
        public static string AllowChangePinPolicyDesc {
            get {
                return ResourceManager.GetString("AllowChangePinPolicyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow default PIN-code usage: {0}.
        /// </summary>
        public static string AllowDefaultPinUsageDesc {
            get {
                return ResourceManager.GetString("AllowDefaultPinUsageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &quot;-{0}&quot; argument should be a number.
        /// </summary>
        public static string ArgumentMustBeIntegerType {
            get {
                return ResourceManager.GetString("ArgumentMustBeIntegerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For changing admin PIN enter old admin PIN.
        /// </summary>
        public static string ChangeAdminPinOldPinError {
            get {
                return ResourceManager.GetString("ChangeAdminPinOldPinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For changing user PIN enter old user or admin PIN.
        /// </summary>
        public static string ChangeUserPinOldPinsError {
            get {
                return ResourceManager.GetString("ChangeUserPinOldPinsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command params count for changing volume attributes. It must be 3.
        /// </summary>
        public static string ChangeVolumeAttributesInvalidCommandParamsCount {
            get {
                return ResourceManager.GetString("ChangeVolumeAttributesInvalidCommandParamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid permanent state.
        /// </summary>
        public static string ChangeVolumeAttributesInvalidPermanentState {
            get {
                return ResourceManager.GetString("ChangeVolumeAttributesInvalidPermanentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to set local user pin.
        /// </summary>
        public static string ChangeVolumeAttributesNeedSetLocalPin {
            get {
                return ResourceManager.GetString("ChangeVolumeAttributesNeedSetLocalPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change volume attributes. For changing volume attributes volume owner PIN is used. If owner is user or admin while PIN isn&apos;t set, default PIN will be used. If owner is local user while local user PIN isn&apos;t set with -O option, error will be occured.
        ///[Volume id: (1 - 9)]
        ///[Access rights: (ro, rw, hi, cd)]
        ///[Change type: (p - permanent, t - temporary)].
        /// </summary>
        public static string ChangeVolumeAttributesOption {
            get {
                return ResourceManager.GetString("ChangeVolumeAttributesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing PIN error.
        /// </summary>
        public static string ChangingPinError {
            get {
                return ResourceManager.GetString("ChangingPinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file is empty.
        /// </summary>
        public static string ConfigFileIsEmpty {
            get {
                return ResourceManager.GetString("ConfigFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config lines have ended.
        /// </summary>
        public static string ConfigFileLinesHaveEnded {
            get {
                return ResourceManager.GetString("ConfigFileLinesHaveEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file not found.
        /// </summary>
        public static string ConfigFileNotFound {
            get {
                return ResourceManager.GetString("ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file should be set.
        /// </summary>
        public static string ConfigurationFileEmpty {
            get {
                return ResourceManager.GetString("ConfigurationFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file path.
        /// </summary>
        public static string ConfigurationFilePathOption {
            get {
                return ResourceManager.GetString("ConfigurationFilePathOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default admin PIN will be used.
        /// </summary>
        public static string DefaultAdminPinWillBeUsed {
            get {
                return ResourceManager.GetString("DefaultAdminPinWillBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default user PIN will be used.
        /// </summary>
        public static string DefaultUserPinWillBeUsed {
            get {
                return ResourceManager.GetString("DefaultUserPinWillBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume create failed.
        /// </summary>
        public static string DriveFormatVolumeCreateFailed {
            get {
                return ResourceManager.GetString("DriveFormatVolumeCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume create passed.
        /// </summary>
        public static string DriveFormatVolumeCreateSuccess {
            get {
                return ResourceManager.GetString("DriveFormatVolumeCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change Admin PIN.
        /// </summary>
        public static string ExampleChangeAdminPin {
            get {
                return ResourceManager.GetString("ExampleChangeAdminPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change Admin PIN, use default new Admin PIN.
        /// </summary>
        public static string ExampleChangeAdminPinWithDefault {
            get {
                return ResourceManager.GetString("ExampleChangeAdminPinWithDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change User PIN.
        /// </summary>
        public static string ExampleChangeUserPin {
            get {
                return ResourceManager.GetString("ExampleChangeUserPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formatting token with generation Admin PIN with length 10 and default User PIN.
        /// </summary>
        public static string ExampleFormatWithAdminPinGeneration {
            get {
                return ResourceManager.GetString("ExampleFormatWithAdminPinGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formatting token with default PIN codes (Admin 87654321, User 12345678).
        /// </summary>
        public static string ExampleFormatWithDefaultPins {
            get {
                return ResourceManager.GetString("ExampleFormatWithDefaultPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:.
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded token serial number should be set in specified format (ex.: 0x46bc3390 or 932436970).
        /// </summary>
        public static string ExcludedTokenSerialEmpty {
            get {
                return ResourceManager.GetString("ExcludedTokenSerialEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded tokens while stream formatting [token ids in specified format: 0x46bc3390 or 932436970]. Use space as serial numbers separator or use option -E for each serial number.
        /// </summary>
        public static string ExcludedTokensOption {
            get {
                return ResourceManager.GetString("ExcludedTokensOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended PIN policies not available.
        /// </summary>
        public static string ExtendedPinPoliciesNotAvailable {
            get {
                return ResourceManager.GetString("ExtendedPinPoliciesNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended PIN policies don&apos;t satisfy PIN policies specified during formatting.
        /// </summary>
        public static string ExtendedPinPolicyDoesntSatisfyTokenPinPolicy {
            get {
                return ResourceManager.GetString("ExtendedPinPolicyDoesntSatisfyTokenPinPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token has no flash memory.
        /// </summary>
        public static string FlashMemoryNotAvailable {
            get {
                return ResourceManager.GetString("FlashMemoryNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access mode.
        /// </summary>
        public static string FormatDriveInvalidAccessMode {
            get {
                return ResourceManager.GetString("FormatDriveInvalidAccessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command params count for drive formatting. It must be 4.
        /// </summary>
        public static string FormatDriveInvalidCommandParamsCount {
            get {
                return ResourceManager.GetString("FormatDriveInvalidCommandParamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid volume size.
        /// </summary>
        public static string FormatDriveInvalidVolumeSize {
            get {
                return ResourceManager.GetString("FormatDriveInvalidVolumeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting error.
        /// </summary>
        public static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format failed : {0} : {1} : SM mode = {2}.
        /// </summary>
        public static string FormatFailed {
            get {
                return ResourceManager.GetString("FormatFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format passed : {0} : {1} : SM mode = {2}.
        /// </summary>
        public static string FormatPassed {
            get {
                return ResourceManager.GetString("FormatPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format memory. If your device has built-in Flash memory you may specify Admin PIN, otherwise you may lose all data on it.
        /// </summary>
        public static string FormatTokenOption {
            get {
                return ResourceManager.GetString("FormatTokenOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting was successful.
        /// </summary>
        public static string FormatTokenSuccess {
            get {
                return ResourceManager.GetString("FormatTokenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format volume. One command for one volume. To create multiple partitions, use the appropriate number of -F commands in sequence. For partition creation admin PIN is used. If it isn&apos;t set, default admin PIN will be used.
        ///[Volume id: (1 - 9)]
        ///[Volume size: volume size in MB]
        ///[Volume owner: (a - administrator, u - user, l3-l9 - local user)]
        ///[Access rights: (ro, rw, hi, cd)].
        /// </summary>
        public static string FormatVolumeParamsOption {
            get {
                return ResourceManager.GetString("FormatVolumeParamsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random Admin PIN code of specified length. If this command is used -a is ignored.
        /// </summary>
        public static string GenerateRandomAdminPinOption {
            get {
                return ResourceManager.GetString("GenerateRandomAdminPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random User PIN code of specified length. If this command is used -u is ignored.
        /// </summary>
        public static string GenerateRandomUserPinOption {
            get {
                return ResourceManager.GetString("GenerateRandomUserPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating activation password(s).
        /// </summary>
        public static string GeneratingActivationPasswords {
            get {
                return ResourceManager.GetString("GeneratingActivationPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting extended PIN policies.
        /// </summary>
        public static string GetExtendedPinPolicies {
            get {
                return ResourceManager.GetString("GetExtendedPinPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting extended PIN policies was failed.
        /// </summary>
        public static string GetExtendedPinPoliciesFailed {
            get {
                return ResourceManager.GetString("GetExtendedPinPoliciesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal options.
        /// </summary>
        public static string IllegalOptions {
            get {
                return ResourceManager.GetString("IllegalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Admin PIN is incorrect.
        /// </summary>
        public static string IncorrectAdminPin {
            get {
                return ResourceManager.GetString("IncorrectAdminPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of extended PIN policies.
        /// </summary>
        public static string IncorrectExtendedPinPolicyUsage {
            get {
                return ResourceManager.GetString("IncorrectExtendedPinPolicyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect OS version.
        /// </summary>
        public static string IncorrectOsVersion {
            get {
                return ResourceManager.GetString("IncorrectOsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered PIN is incorrect.
        /// </summary>
        public static string IncorrectPin {
            get {
                return ResourceManager.GetString("IncorrectPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect volume owner PIN.
        /// </summary>
        public static string IncorrectVolumeOwnerPin {
            get {
                return ResourceManager.GetString("IncorrectVolumeOwnerPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application was initialized.
        /// </summary>
        public static string InitializedInfo {
            get {
                return ResourceManager.GetString("InitializedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid max Admin PIN retry count. It must be in the range from 3 to 10.
        /// </summary>
        public static string InvalidMaxAdminPinRetryCount {
            get {
                return ResourceManager.GetString("InvalidMaxAdminPinRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid max User PIN retry count. It must be in the range from 1 to 10.
        /// </summary>
        public static string InvalidMaxUserPinRetryCount {
            get {
                return ResourceManager.GetString("InvalidMaxUserPinRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid minimal admin PIN length. It must be from 1 to 31 symbols.
        /// </summary>
        public static string InvalidMinimalAdminPinLength {
            get {
                return ResourceManager.GetString("InvalidMinimalAdminPinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid minimal user PIN length. It must be from 1 to 31 symbols.
        /// </summary>
        public static string InvalidMinimalUserPinLength {
            get {
                return ResourceManager.GetString("InvalidMinimalUserPinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid policy value. It must be from 1 to 3.
        /// </summary>
        public static string InvalidPolicyValue {
            get {
                return ResourceManager.GetString("InvalidPolicyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user pin change policy.
        /// </summary>
        public static string InvalidUserPinChangePolicy {
            get {
                return ResourceManager.GetString("InvalidUserPinChangePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file path.
        /// </summary>
        public static string LogFilePathOption {
            get {
                return ResourceManager.GetString("LogFilePathOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Login with local PIN. In order to use local user set his new PIN preliminarily.
        ///[Id: local PIN id (l3 - l9)]
        ///[PIN: local PIN].
        /// </summary>
        public static string LoginWithLocalPinOption {
            get {
                return ResourceManager.GetString("LoginWithLocalPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max PIN code attempts count for Admin PIN (count must be in the range from 3 to 10; default: 6).
        /// </summary>
        public static string MaxAdminPinAttemptsOption {
            get {
                return ResourceManager.GetString("MaxAdminPinAttemptsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max PIN code attempts count for User PIN (count must be in the range from 3 to 10; default: 6).
        /// </summary>
        public static string MaxUserPinAttemptsOption {
            get {
                return ResourceManager.GetString("MaxUserPinAttemptsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Admin PIN code length (length must be in the range from 1 to 31; default: 6). Ignore for Rutoken S(use 1 only).
        /// </summary>
        public static string MinAdminPinLengthOption {
            get {
                return ResourceManager.GetString("MinAdminPinLengthOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min PIN Length: {0}.
        /// </summary>
        public static string MinPinLengthDesc {
            get {
                return ResourceManager.GetString("MinPinLengthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min User PIN code length (length must be in the range from 1 to 31; default: 6). Ignore for Rutoken S(use 1 only).
        /// </summary>
        public static string MinUserPinLengthOption {
            get {
                return ResourceManager.GetString("MinUserPinLengthOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native library file should be set.
        /// </summary>
        public static string NativeLibraryFileEmpty {
            get {
                return ResourceManager.GetString("NativeLibraryFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open native library at the specified path.
        /// </summary>
        public static string NativeLibraryFileInvalid {
            get {
                return ResourceManager.GetString("NativeLibraryFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native library file doesn&apos;t exist at the specified path.
        /// </summary>
        public static string NativeLibraryFileNotExist {
            get {
                return ResourceManager.GetString("NativeLibraryFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a native library to use.
        /// </summary>
        public static string NativeLibraryPathOption {
            get {
                return ResourceManager.GetString("NativeLibraryPathOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command params for using local PIN. It must be 2 command line params.
        /// </summary>
        public static string NewLocalPinInvalidCommandParamsCount {
            get {
                return ResourceManager.GetString("NewLocalPinInvalidCommandParamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid local user id.
        /// </summary>
        public static string NewLocalPinInvalidOwnerId {
            get {
                return ResourceManager.GetString("NewLocalPinInvalidOwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set local PIN.
        /// </summary>
        public static string NewLocalPinSetFailed {
            get {
                return ResourceManager.GetString("NewLocalPinSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local PIN has been successfully set.
        /// </summary>
        public static string NewLocalPinSetSuccess {
            get {
                return ResourceManager.GetString("NewLocalPinSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Admin PIN code. Must be specified for Admin PIN changing.
        /// </summary>
        public static string OldAdminPinOption {
            get {
                return ResourceManager.GetString("OldAdminPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Admin PIN: .
        /// </summary>
        public static string OldAdminPinPrompt {
            get {
                return ResourceManager.GetString("OldAdminPinPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old User PIN code. Must be specified for User PIN changing.
        /// </summary>
        public static string OldUserPinOption {
            get {
                return ResourceManager.GetString("OldUserPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User PIN: .
        /// </summary>
        public static string OldUserPinPrompt {
            get {
                return ResourceManager.GetString("OldUserPinPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop after one iteration.
        /// </summary>
        public static string OneIterationOnlyOption {
            get {
                return ResourceManager.GetString("OneIterationOnlyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while sending request for setting PIN2 PINPad.
        /// </summary>
        public static string Pin2SetFailed {
            get {
                return ResourceManager.GetString("Pin2SetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN2 PINPad set request has been successfully sent.
        /// </summary>
        public static string Pin2SetSuccess {
            get {
                return ResourceManager.GetString("Pin2SetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by admin.
        /// </summary>
        public static string PinChangeByAdmin {
            get {
                return ResourceManager.GetString("PinChangeByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN changed successfully.
        /// </summary>
        public static string PinChangedSuccess {
            get {
                return ResourceManager.GetString("PinChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pin change failed.
        /// </summary>
        public static string PinChangeFailed {
            get {
                return ResourceManager.GetString("PinChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pin change {1} passed : {2} : {3}.
        /// </summary>
        public static string PinChangePassed {
            get {
                return ResourceManager.GetString("PinChangePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set PIN change policy. Default value - 2.
        ///[(1 - administrator (SO) can change user PIN), (2 - user can change user PIN), (3 - both)].
        /// </summary>
        public static string PinChangePolicyOption {
            get {
                return ResourceManager.GetString("PinChangePolicyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN-codes file contains incorrect number of PINs.
        /// </summary>
        public static string PinCodesFileIncorrectLinesCount {
            get {
                return ResourceManager.GetString("PinCodesFileIncorrectLinesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN-codes file is empty.
        /// </summary>
        public static string PinCodesFileIsEmpty {
            get {
                return ResourceManager.GetString("PinCodesFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin codes file name should be set.
        /// </summary>
        public static string PinCodesFileNameEmpty {
            get {
                return ResourceManager.GetString("PinCodesFileNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN-codes file not found.
        /// </summary>
        public static string PinCodesFileNotFound {
            get {
                return ResourceManager.GetString("PinCodesFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN-codes from file have ended.
        /// </summary>
        public static string PinCodesFilePinsHaveEnded {
            get {
                return ResourceManager.GetString("PinCodesFilePinsHaveEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN requires digits: {0}.
        /// </summary>
        public static string PinContainsDigitDesc {
            get {
                return ResourceManager.GetString("PinContainsDigitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN requires lowercase letter: {0}.
        /// </summary>
        public static string PinContainsLowerLetterDesc {
            get {
                return ResourceManager.GetString("PinContainsLowerLetterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN requires spec. chars: {0}.
        /// </summary>
        public static string PinContainsSpecCharDesc {
            get {
                return ResourceManager.GetString("PinContainsSpecCharDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN requires uppercase letter: {0}.
        /// </summary>
        public static string PinContainsUpperLetterDesc {
            get {
                return ResourceManager.GetString("PinContainsUpperLetterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load new PIN codes from specified file. Use not PIN per line, \n is separator. -a -u -G -g commands are ignored.
        /// </summary>
        public static string PinFilePathOption {
            get {
                return ResourceManager.GetString("PinFilePathOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t generate pin. Change Token.
        /// </summary>
        public static string PinGenerationError {
            get {
                return ResourceManager.GetString("PinGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t generate pin. This token was skipped.
        /// </summary>
        public static string PinGenerationFailed {
            get {
                return ResourceManager.GetString("PinGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN history depth: {0}.
        /// </summary>
        public static string PinHistoryDepthDesc {
            get {
                return ResourceManager.GetString("PinHistoryDepthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN length and allowed PIN length mismatch. Min admin PIN length: {0}, max admin PIN length: {1}, min user PIN length: {2}, max user PIN length: {3}.
        /// </summary>
        public static string PinLengthMismatch {
            get {
                return ResourceManager.GetString("PinLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN length and allowed PIN length mismatch. Length must be in the range from 1 to 31; default: 6.
        /// </summary>
        public static string PinLengthMismatchBeforeFormat {
            get {
                return ResourceManager.GetString("PinLengthMismatchBeforeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock PIN failed.
        /// </summary>
        public static string PinUnlockFailed {
            get {
                return ResourceManager.GetString("PinUnlockFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock PIN passed.
        /// </summary>
        public static string PinUnlockSuccess {
            get {
                return ResourceManager.GetString("PinUnlockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: PKCS#11 library code:.
        /// </summary>
        public static string PKCS11Error {
            get {
                return ResourceManager.GetString("PKCS11Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New random Admin PIN length and allowed PIN length mismatch, min PIN length: {0}, max PIN length: {1}.
        /// </summary>
        public static string RandomAdminPinLengthMismatch {
            get {
                return ResourceManager.GetString("RandomAdminPinLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New random User PIN length and allowed PIN length mismatch, min PIN length: {0}, max PIN length: {1}.
        /// </summary>
        public static string RandomUserPinLengthMismatch {
            get {
                return ResourceManager.GetString("RandomUserPinLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN policies will be deleted after format: {0}.
        /// </summary>
        public static string RemovePinPolicyAfterFormatDesc {
            get {
                return ResourceManager.GetString("RemovePinPolicyAfterFormatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN requires different char usage: {0}.
        /// </summary>
        public static string RestrictOneCharPinDesc {
            get {
                return ResourceManager.GetString("RestrictOneCharPinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number should be specified.
        /// </summary>
        public static string SerialNumberEmpty {
            get {
                return ResourceManager.GetString("SerialNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify token serial number to use.
        /// </summary>
        public static string SerialNumberOption {
            get {
                return ResourceManager.GetString("SerialNumberOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting extended PIN policies.
        /// </summary>
        public static string SetExtendedPinPolicies {
            get {
                return ResourceManager.GetString("SetExtendedPinPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting extended PIN policies was failed.
        /// </summary>
        public static string SetExtendedPinPoliciesFailed {
            get {
                return ResourceManager.GetString("SetExtendedPinPoliciesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set extended PIN policies
        ///[Usage: --set-expp (pin_policy_opt1) (value1) (pin_policy_opt2) (value2) ... ].
        /// </summary>
        public static string SetExtendedPinPolicyOption {
            get {
                return ResourceManager.GetString("SetExtendedPinPolicyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set local PIN.
        ///[Id: local PIN id (l3 - l9)]
        ///[PIN: local PIN].
        /// </summary>
        public static string SetLocalPinOption {
            get {
                return ResourceManager.GetString("SetLocalPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate setting PIN2-code (on the screen mode) for PINPad..
        /// </summary>
        public static string SetPin2ModeOption {
            get {
                return ResourceManager.GetString("SetPin2ModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to set formatting option -f.
        /// </summary>
        public static string ShouldSetFormatOption {
            get {
                return ResourceManager.GetString("ShouldSetFormatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show extended PIN policies.
        /// </summary>
        public static string ShowExtendedPinPolicyOption {
            get {
                return ResourceManager.GetString("ShowExtendedPinPolicyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show help message.
        /// </summary>
        public static string ShowHelp {
            get {
                return ResourceManager.GetString("ShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show application version.
        /// </summary>
        public static string ShowVersion {
            get {
                return ResourceManager.GetString("ShowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set SM mode (only for Bluetooth token).
        ///[Passwords: (1 - optional password), (2 - 1 password), (3 - 6 passwords)] 
        ///[Mode: (caps - only capital letters), (digits - capital letters and digits)].
        /// </summary>
        public static string SmModeOption {
            get {
                return ResourceManager.GetString("SmModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get user and admin PINs from stdin if they value equal &quot;stdin&quot;.
        /// </summary>
        public static string StdinPinsOption {
            get {
                return ResourceManager.GetString("StdinPinsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Id.
        /// </summary>
        public static string TokenId {
            get {
                return ResourceManager.GetString("TokenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change token label.
        /// </summary>
        public static string TokenLabelChangeFailed {
            get {
                return ResourceManager.GetString("TokenLabelChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token label changed successfully.
        /// </summary>
        public static string TokenLabelChangeSuccess {
            get {
                return ResourceManager.GetString("TokenLabelChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use cp1251 for new device label.
        /// </summary>
        public static string TokenLabelCp1251Option {
            get {
                return ResourceManager.GetString("TokenLabelCp1251Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token label should be set.
        /// </summary>
        public static string TokenLabelEmpty {
            get {
                return ResourceManager.GetString("TokenLabelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change token label. Enter user PIN using -c.
        /// </summary>
        public static string TokenLabelPinError {
            get {
                return ResourceManager.GetString("TokenLabelPinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use UTF-8 for new device label.
        /// </summary>
        public static string TokenLabelUtf8Option {
            get {
                return ResourceManager.GetString("TokenLabelUtf8Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token params were not set.
        /// </summary>
        public static string TokenParamsNotSet {
            get {
                return ResourceManager.GetString("TokenParamsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total disk size.
        /// </summary>
        public static string TotalDriveSize {
            get {
                return ResourceManager.GetString("TotalDriveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting total disk size.
        /// </summary>
        public static string TotalDriveSizeFailed {
            get {
                return ResourceManager.GetString("TotalDriveSizeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock user and local PINs. You should use login with Admin PIN command to unblock user and local PINs.
        /// </summary>
        public static string UnblockPinsOption {
            get {
                return ResourceManager.GetString("UnblockPinsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error:.
        /// </summary>
        public static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user PIN.
        /// </summary>
        public static string UserPin {
            get {
                return ResourceManager.GetString("UserPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter {0} according to user PIN change policy on token.
        /// </summary>
        public static string UserPinChangePolicyError {
            get {
                return ResourceManager.GetString("UserPinChangePolicyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set User PIN code. Must be specified for Admin PIN changing. If not specified, the default value is used.
        /// </summary>
        public static string UserPinOption {
            get {
                return ResourceManager.GetString("UserPinOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string UserPinOwner {
            get {
                return ResourceManager.GetString("UserPinOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User PIN: .
        /// </summary>
        public static string UserPinPrompt {
            get {
                return ResourceManager.GetString("UserPinPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use UTF-8 instead of cp1251 in PIN codes.
        /// </summary>
        public static string Utf8Option {
            get {
                return ResourceManager.GetString("Utf8Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume access mode change failed.
        /// </summary>
        public static string VolumeAccessModeChangeFailed {
            get {
                return ResourceManager.GetString("VolumeAccessModeChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume access mode change passed.
        /// </summary>
        public static string VolumeAccessModeChangeSuccess {
            get {
                return ResourceManager.GetString("VolumeAccessModeChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume attributes store is not set.
        /// </summary>
        public static string VolumeAttributesStoreNotSet {
            get {
                return ResourceManager.GetString("VolumeAttributesStoreNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For -i argument should be set.
        /// </summary>
        public static string VolumeInfoEmpty {
            get {
                return ResourceManager.GetString("VolumeInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting volumes info.
        /// </summary>
        public static string VolumeInfoGettingFailed {
            get {
                return ResourceManager.GetString("VolumeInfoGettingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid volume id.
        /// </summary>
        public static string VolumeInfoInvalidVolumeId {
            get {
                return ResourceManager.GetString("VolumeInfoInvalidVolumeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume with specified id not found.
        /// </summary>
        public static string VolumeInfoNotFound {
            get {
                return ResourceManager.GetString("VolumeInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get volumes or drive info.
        ///[Parameter: (volume id: 1 - 9), (all volumes: a), (flash size: sz)].
        /// </summary>
        public static string VolumeInfoParamsOption {
            get {
                return ResourceManager.GetString("VolumeInfoParamsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume owners store is not set.
        /// </summary>
        public static string VolumeOwnersStoreNotSet {
            get {
                return ResourceManager.GetString("VolumeOwnersStoreNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next token... (Or press &quot;q&quot;).
        /// </summary>
        public static string WaitingNextToken {
            get {
                return ResourceManager.GetString("WaitingNextToken", resourceCulture);
            }
        }
    }
}
